### ISSUE TITLE
Responsive for small screens

### ISSUE THREAD

**Issue by surya-doc** [N-Shar-ma/Emoji-Card-Game#10]
* The pages are not responsive for different screens. Would like to work on this issue.
![image](https://user-images.githubusercontent.com/69008196/193437850-50b5c3f2-bcf7-47b1-920c-96366a7d181f.png)

**Comment by N-Shar-ma** [comment]
The drag and drop works anyway with only a mouse and not touch screens (at least right now) so there's no real need to make the site responsive for touch devices
