### ISSUE TITLE
Adding sound effects on correct and wrong guess

### ISSUE THREAD

**Issue by DevilzzNikhil** [N-Shar-ma/Emoji-Card-Game#12]
Playing music on incorrect and correct ans and Add feature to reveal ans after all trials @N-Shar-ma

**Comment by DevilzzNikhil** [comment]
I would like to work on this

**Comment by N-Shar-ma** [comment]
Hmm, this might be a nice addition. What audio / music exactly do you have in mind for correct and incorrect answer? Also how would you go about revealing all answers at the end?

**Comment by DevilzzNikhil** [comment]
@N-Shar-ma  not sure about answers but for music i have some game music for that some https://www.storyblocks.com/audio/search/correct+answer+sound+1+sound+effect i can use this website for that 

and for answers i think we can tell the correct ans after end of 3 trials

**Comment by N-Shar-ma** [comment]
@DevilzzNikhil For now, the sound effects on correct and wrong guess seems like a feature I'd like to be present in the game. Simple bright sounds should go well with the game's feel. Additionally please add a volume icon in the top right of the game screen to toggle sound on and off. Looking forward to a PR!

**Comment by N-Shar-ma** [comment]
@DevilzzNikhil Any updates?

**Comment by Gauravdarkslayer** [comment]
Hey @N-Shar-ma is @DevilzzNikhil still on it, if not then you can assign this issue to me.
Thank you !!

**Comment by N-Shar-ma** [comment]
Go ahead, @Gauravdarkslayer !
