### ISSUE TITLE
Bug: Instructions button not working?

### ISSUE THREAD

**Issue by deep-69bits** [N-Shar-ma/Emoji-Card-Game#25]
## Want to add instructions on clicking instruction button
<img src="https://user-images.githubusercontent.com/96793524/193748819-df11324f-72da-4b5d-90d4-5cd55a8cc7bd.gif">

**Comment by N-Shar-ma** [comment]
@deep-69bits This seems like a weird bug. For me everything works fine (the instructions do show up) on Chrome, Edge and Firefox on Windows 10. Could you maybe investigate in which cases this bug occurs? 

(And please check if you have mistakenly altered the code causing this bug locally)

Anyone else facing a similar issue, please report here!

**Comment by deep-69bits** [comment]
@N-Shar-ma  
## I have checked the code again there was error from my side sorry
