### ISSUE TITLE
Adding logo with name, a favicon and also a footer

### ISSUE THREAD

**Issue by InquisitiveMe15** [N-Shar-ma/Emoji-Card-Game#27]
Hello! @N-Shar-ma 
Adding logo, favicon and a nice footer will make the website look more professional.
If you find this helpful and interesting please assign this issue to me.

Thank you :)

**Comment by N-Shar-ma** [comment]
@InquisitiveMe15 Since we are in the process of renaming the game, and all of the proposed additions depend on that, I'll be closing the issue for now (and maybe reopening it later when the need arises). Thanks for the suggestions though!

**Comment by InquisitiveMe15** [comment]
Yeah sure, no problem :)
