### ISSUE TITLE
Deck Idea : Harry Potter

### ISSUE THREAD

**Issue by Ni-vik** [N-Shar-ma/Emoji-Card-Game#28]
I would like to create a deck of Harry Potter characters.

**Comment by N-Shar-ma** [comment]
@Ni-vik Sounds like a great idea! Please go through the newly added instructions [here](https://github.com/N-Shar-ma/Emoji-Card-Game/blob/master/CONTRIBUTING.md?rgh-link-date=2022-10-01T15%3A14%3A51Z#detailed-instructions-for-adding-a-new-deck-of-cards) to add a new deck :)

PS: you can edit this very issue to add the content needed following the instructions!
