### ISSUE TITLE
Drag and drop doesn't work on touch devices 

### ISSUE THREAD

**Issue by yohanesgultom** [N-Shar-ma/Emoji-Card-Game#31]
Has anyone try this app from android phone? Drag and drop doesn't seems to work. Usually we can tap an element for few seconds dan drag it. But in this case, a card would just turn transparent but not draggable 

https://user-images.githubusercontent.com/1680876/193946903-d16209bc-4c05-412e-a616-fd86b011dfc4.mp4

**Comment by N-Shar-ma** [comment]
@yohanesgultom thank you for creating this issue! Yes, currently the game does not support touch devices, as the drag and drop only works via mouse / touchpad.

However, if more than a few people would like to have the game work on touch / mobiles devices as well, we could try to update the code, and use a different, more versatile drag and drop API, to make it work on those devices as well!

Those who feel that this game would be fun to play on mobile phones as well, please react with the 🚀 emoji to make yourselves be heard!
