### ISSUE TITLE
Softer Shadows

### ISSUE THREAD

**Issue by thevinitgupta** [N-Shar-ma/Emoji-Card-Game#36]
Looking at the design, I would like suggest software shadows on sections.

So something like this would look better : 
![Screenshot (263)](https://user-images.githubusercontent.com/65801700/194073421-2f67b7d7-ee2a-4075-a6a4-d23f3c25a917.png)

I would love to be assigned to this if accepted.

**Comment by N-Shar-ma** [comment]
Hmm that does look better! To make sure your PR isn't too small so not in danger of being considered spam, could you also make a couple more changes:
- remove the negative margin-top on the anchor element for leaving a star on GitHub
- make the background color of the desk author display at the bottom opaque white

Once you confirm, I'll assign this to you!

**Comment by thevinitgupta** [comment]
Sure I would love to.
Please assign me.
