### ISSUE TITLE
Deck Idea : Netflix series 

### ISSUE THREAD

**Issue by kat-kan** [N-Shar-ma/Emoji-Card-Game#37]
Hi, as agreed - I'd like to add this category to the game. Please assign to me :)

**Comment by N-Shar-ma** [comment]
@kat-kan Could you please 1st give a couple of example cards as mentioned [here](https://github.com/N-Shar-ma/Emoji-Card-Game/blob/master/CONTRIBUTING.md?rgh-link-date=2022-10-01T15%3A14%3A51Z#detailed-instructions-for-adding-a-new-deck-of-cards) in the last point in bold? I'll assign this to you after that. Just following the standard procedure :)

**Comment by kat-kan** [comment]
Oooh I'm sorry :( didn't notice. 
I was thinking about big popular titles like Stranger Things, The Bridgertons, The Umbrella Academy etc :)

**Comment by N-Shar-ma** [comment]
It's alright! And sure, that sounds good!

(By giving example cards I actually meant something like [this](https://github.com/N-Shar-ma/Emoji-Card-Game/issues/19#issuecomment-1265964556) but it's okay, I really liked your fantasy fiction deck so I'm sure you'll do a good job with this one too!)

**Comment by kat-kan** [comment]
Hello @N-Shar-ma I updated my comment just to show the others an example how it should look like :) 

Btw is putting "Sex Education" series in my deck enough SFW? :)

**Comment by N-Shar-ma** [comment]
@kat-kan Thanks for the examples! And yes, do include that series for now in your PR, I'll consider having it or not once the PR is made :)
