### ISSUE TITLE
Button/link to go back to the home screen

### ISSUE THREAD

**Issue by julicheng** [N-Shar-ma/Emoji-Card-Game#43]
I would like to work on adding a button or link to go back to the home screen once a game has started. With the current implementation, the only way to start another game is to reload the page.

Let me know what your thoughts are 🙂

**Comment by N-Shar-ma** [comment]
That sounds like a great idea! It'll be nice if you could discuss and finalize the position and styling of that button here before making the PR though :)

**Comment by julicheng** [comment]
I was thinking bottom left or top right with similar styling to what you have for the hints and the score element but in a different colour like grey so it's not so eye-catching 🤔

**Comment by N-Shar-ma** [comment]
Top right grey sounds good! Lets go ahead with that, and if need be we can tweak once the PR is made.
