### ISSUE TITLE
Reponsive UI for better experience

### ISSUE THREAD

**Issue by thevinitgupta** [N-Shar-ma/Emoji-Card-Game#46]
The game works good for Desktops but having a UI that is responsive would be better. 
For smaller screens the game looks something like this : 

![breaking](https://user-images.githubusercontent.com/65801700/194351157-62fc93ac-49b6-4c8b-bf8e-3e1720ee0030.PNG)

A better looking UI would be something like this : 
![better](https://user-images.githubusercontent.com/65801700/194351245-d8b22cb6-fa77-4700-b2ed-b95e36d90b29.PNG)

I would love to implement this.

**Comment by thevinitgupta** [comment]
Sure I would.
Thanks

**Comment by thevinitgupta** [comment]
I am having trouble using `Media Queries`. 
The website is not reading any styles I put inside media query blocks.
Is there a reason for this?

**Comment by N-Shar-ma** [comment]
@thevinitgupta You probably need to add in this line in the header in the html:
`<meta name="viewport" content="width=device-width, initial-scale=1.0">`

**Comment by thevinitgupta** [comment]
Yes it is working fine now.
Thanks
