### ISSUE TITLE
To use custom modal boxes instead of native `alert()` and `confirm()` calls

### ISSUE THREAD

**Issue by jalaj711** [N-Shar-ma/Emoji-Card-Game#47]
Rather than using the built-in functions `alert()` and/or `confirm()` for user interaction, I think that it would be better if we use custom modal boxes built on HTML/CSS/JS. Doing this will present the following benefits:

- The entire User Experience can be more consistent with the theme of the rest of the website.
- Users on different browsers will still have the same experience, as the UI won't be left on the mercy of the browser.
- We can add more animations over there as well.

**Comment by jalaj711** [comment]
If the idea sounds good, I can implement this.

**Comment by N-Shar-ma** [comment]
@jalaj711 Thanks for creating the issue! Custom modals are something that have always been on the todo list, so would indeed love having them!

PS: Please consider a similar way of creating and using modals like in [this](https://github.com/N-Shar-ma/Meals-From-Around-The-World) older project of mine (mainly referring to the use of html template elements a customizable function like `showModal`) but if you have any alternative ideas, would appreciate you discussing those here too!
