### ISSUE TITLE
A Deck of Countries

### ISSUE THREAD

**Issue by RaginaPhalangae** [N-Shar-ma/Emoji-Card-Game#53]
I would like to add an new deck of countries . Kindly assign me this issue

**Comment by N-Shar-ma** [comment]
@RaginaPhalangae  Thanks for the suggestion, it sounds promising! Please go through the instructions [here](https://github.com/N-Shar-ma/Emoji-Card-Game/blob/master/CONTRIBUTING.md?rgh-link-date=2022-10-04T18%3A48%3A10Z#detailed-instructions-for-adding-a-new-deck-of-cards) to add a new deck :)

Note that you **need to propose a couple of example cards here (in this issue) and then I'll assign this to you** to work on the full deck if those look good!
