### ISSUE TITLE
Add feature to show credits for each deck's creator

### ISSUE THREAD

**Issue by N-Shar-ma** [N-Shar-ma/Emoji-Card-Game#6]
Each deck in this game is someone's brain child and deserves to be easily linked with it's creator!

Would appreciate if someone could add a field for the GitHub username (and optionally the full real name) of the creator of the deck in each deck object in the `decks.js` file, and then display it alongside the deck name in the category dropdown menu, and also later while playing through a deck. Specifics of how and where to show the name are open to discussion (which is encouraged!).

Figuring out the creator for each deck should be easy going through the commit history / PRs.

**Comment by McCune1224** [comment]
Id be happy to work on this, should be as easy as adding another property called author to the decks with.js file for each deck.

If its okay, a tweak to the 'Contributing' section too mentioning for future deck makers to include their name in the author field would help too.

**Comment by McCune1224** [comment]
Also, as for where to display the author, 2 places came to mind:

1.  A new line underneath the card depicted box with the author name would be a good spot. Might be a tight fit however with the yellow box.

3. At the bottom of the screen with the same design as the card depicted box.

**Comment by N-Shar-ma** [comment]
That sounds like a great plan, @McCune1224! Appreciate the suggested tweak to the `Contributing` section as well. 

I'd definitely prefer the 2nd location (at the bottom of the screen) for the author display since there's more room there. 

Looking forward to your PR!
