### ISSUE TITLE
Add github pages to readme

### ISSUE THREAD

**Issue by PrashanthKumar0** [N-Shar-ma/Emoji-Card-Game#9]
Please add github pages in the repo itself , so that we can play it live before cloning the repo.
This is quickest way for many contributors to see if they really can/want to , contribute.

**Comment by N-Shar-ma** [comment]
Hm, the live link (for the netlify site) is already there, but yeah it should ideally be present in the readme too. Thanks for the suggestion; since this is a tiny update, I'll make it myself
